
package hmod.launcher.running;

import hmod.core.Algorithm;
import hmod.core.AlgorithmException;
import java.awt.event.WindowEvent;
import javax.swing.JDialog;
import javax.swing.text.DefaultCaret;
import optefx.util.output.SystemOutputConfigBuilder;

/**
 *
 * @author Enrique Urra C.
 */
class WindowedAlgorithmInterface extends JDialog implements AlgorithmInterface
{
    private AlgorithmFrameWriter writer;
    private Algorithm algorithm;
    private boolean autoClose;
    private boolean closed;
    
    public WindowedAlgorithmInterface(String name, boolean threading, boolean autoClose)
    {        
        initComponents();
        DefaultCaret caret = (DefaultCaret)jTextArea1.getCaret();
        caret.setUpdatePolicy(DefaultCaret.ALWAYS_UPDATE);        
        setTitle("Algorithm execution: '" + name + "'");
        
        if(!threading)
            setModalityType(ModalityType.APPLICATION_MODAL);
        
        this.writer = new AlgorithmFrameWriter(jTextArea1);
        this.autoClose = autoClose;
    }

    /*public void setAlgorithmThread(Thread algorithmThread)
    {
    this.algorithmThread = algorithmThread;
    }*/
    /*@Override
    public void setVisible(boolean bln)
    {
    if(listenerThread != null)
    listenerThread.start();
    super.setVisible(bln);
    }*/
    @Override
    public void configOutputs(SystemOutputConfigBuilder outputConfigBuilder)
    {
        outputConfigBuilder.setSystemOutput(writer);
    }
    
    @Override
    public void init(Algorithm algorithm, final Thread algorithmThread)
    {
        this.algorithm = algorithm;
        
        
        Thread thread = new Thread()
        {
            @Override
            public void run()
            {
                try
                {
                    algorithmThread.join();
                }
                catch(InterruptedException ex)
                {                    
                }
                finally
                {
                    WindowedAlgorithmInterface.this.jButton1.setText("Stopped");
                    WindowedAlgorithmInterface.this.jButton1.setEnabled(false);
                    
                    if(autoClose && !WindowedAlgorithmInterface.this.closed)
                        WindowedAlgorithmInterface.this.dispatchEvent(new WindowEvent(WindowedAlgorithmInterface.this, WindowEvent.WINDOW_CLOSING));
                }
            }
        };
        
        thread.start();
        setVisible(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setIconImage(null);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter()
        {
            public void windowClosing(java.awt.event.WindowEvent evt)
            {
                formWindowClosing(evt);
            }
        });

        jLabel1.setText("Output:");

        jTextArea1.setColumns(20);
        jTextArea1.setEditable(false);
        jTextArea1.setRows(5);
        jTextArea1.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                jTextArea1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTextArea1);

        jButton1.setText("Stop execution");
        jButton1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton1ActionPerformed(evt);
            }
        });

        jCheckBox1.setSelected(true);
        jCheckBox1.setText("Auto-scroll");
        jCheckBox1.addItemListener(new java.awt.event.ItemListener()
        {
            public void itemStateChanged(java.awt.event.ItemEvent evt)
            {
                jCheckBox1ItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 781, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jCheckBox1)
                        .addGap(583, 583, 583)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addGap(6, 6, 6)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jCheckBox1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox1ItemStateChanged(java.awt.event.ItemEvent evt)//GEN-FIRST:event_jCheckBox1ItemStateChanged
    {//GEN-HEADEREND:event_jCheckBox1ItemStateChanged
        DefaultCaret caret = (DefaultCaret)jTextArea1.getCaret();
        
        if(jCheckBox1.isSelected())
        {
            jTextArea1.setCaretPosition(jTextArea1.getDocument().getLength());
            caret.setUpdatePolicy(DefaultCaret.ALWAYS_UPDATE);
        }
        else
        {
            caret.setUpdatePolicy(DefaultCaret.NEVER_UPDATE);
        }
    }//GEN-LAST:event_jCheckBox1ItemStateChanged

    private void formWindowClosing(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowClosing
    {//GEN-HEADEREND:event_formWindowClosing
        closed = true;
        
        try
        {
            algorithm.stop();
        }
        catch(AlgorithmException ex)
        {
        }
        
        //algorithmThread.interrupt();
        //algorithmThread.interrupt();
    }//GEN-LAST:event_formWindowClosing

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton1ActionPerformed
    {//GEN-HEADEREND:event_jButton1ActionPerformed
        jButton1.setText("Stopping...");
        jButton1.setEnabled(false);
        
        try
        {
            algorithm.stop();
        }
        catch(AlgorithmException ex)
        {
        }
        
        //algorithmThread.interrupt();
        //algorithmThread.interrupt();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextArea1MouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jTextArea1MouseClicked
    {//GEN-HEADEREND:event_jTextArea1MouseClicked
        if(jCheckBox1.isSelected())
        {
            DefaultCaret caret = (DefaultCaret)jTextArea1.getCaret();
            caret.setUpdatePolicy(DefaultCaret.NEVER_UPDATE);
            jCheckBox1.setSelected(false);
        }
    }//GEN-LAST:event_jTextArea1MouseClicked
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
